name: uniformizing-3D
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _anaconda_depends=2019.03=py36_0
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.8.1=py36_0
  - alabaster=0.7.12=py36_0
  - albumentations=0.4.3=py_0
  - anaconda=custom=py36_1
  - anaconda-client=1.7.2=py36_0
  - anaconda-project=0.8.4=py_0
  - asn1crypto=1.3.0=py36_0
  - astor=0.8.0=py36_0
  - astroid=2.3.3=py36_0
  - astropy=4.0=py36h7b6447c_0
  - atomicwrites=1.3.0=py36_1
  - attrs=19.3.0=py_0
  - babel=2.8.0=py_0
  - backcall=0.1.0=py36_0
  - backports=1.0=py_2
  - backports.os=0.1.1=py36_0
  - backports.shutil_get_terminal_size=1.0.0=py36_2
  - beautifulsoup4=4.8.2=py36_0
  - bitarray=1.2.0=py36h7b6447c_0
  - bkcharts=0.2=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - blosc=1.17.0=he1b5a44_1
  - bokeh=1.4.0=py36_0
  - boto=2.49.0=py36_0
  - bottleneck=1.3.1=py36hdd07704_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2019.11.28=hecc5488_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.11.28=py36_0
  - cffi=1.13.2=py36h2e261b9_0
  - chardet=3.0.4=py36_1003
  - click=7.0=py36_0
  - cloudpickle=1.2.2=py_0
  - clyent=1.2.2=py36_1
  - colorama=0.4.3=py_0
  - contextlib2=0.6.0.post1=py_0
  - cryptography=2.8=py36h1ba5d50_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cupti=10.0.130=0
  - curl=7.67.0=hbc83047_0
  - cycler=0.10.0=py36_0
  - cython=0.29.14=py36he6710b0_0
  - cytoolz=0.10.1=py36h7b6447c_0
  - dask=2.9.1=py_0
  - dask-core=2.9.1=py_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - distributed=2.9.1=py_0
  - docutils=0.15.2=py36_0
  - entrypoints=0.3=py36_0
  - et_xmlfile=1.0.1=py36_0
  - expat=2.2.6=he6710b0_0
  - fastcache=1.1.0=py36h7b6447c_0
  - ffmpeg=4.1.3=h167e202_0
  - flask=1.1.1=py_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - fsspec=0.6.2=py_0
  - gast=0.2.2=py36_0
  - geos=3.8.0=he1b5a44_0
  - get_terminal_size=1.0.0=haa9412d_0
  - gevent=1.4.0=py36h7b6447c_0
  - giflib=5.2.1=h516909a_1
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=h6c8ec71_1
  - gmpy2=2.0.8=py36h10f8cd9_2
  - gnutls=3.6.5=hd3a4fd2_1002
  - google-pasta=0.1.8=py_0
  - graphite2=1.3.13=h23475e2_0
  - greenlet=0.4.15=py36h7b6447c_0
  - grpcio=1.16.1=py36hf8bcb03_1
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - h5py=2.10.0=nompi_py36h513d04c_101
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - heapdict=1.0.1=py_0
  - html5lib=1.0.1=py36_0
  - hypothesis=4.54.2=py36_0
  - icu=64.2=he1b5a44_1
  - idna=2.8=py36_0
  - imageio=2.6.1=py36_0
  - imagesize=1.2.0=py_0
  - imgaug=0.3.0=py_0
  - importlib_metadata=1.3.0=py36_0
  - intel-openmp=2019.4=243
  - ipykernel=5.1.3=py36h39e3cac_0
  - ipython=7.11.1=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py36_0
  - itsdangerous=1.1.0=py36_0
  - jasper=1.900.1=h07fcdf6_1006
  - jbig=2.1=hdba287a_0
  - jdcal=1.4.1=py_0
  - jedi=0.15.2=py36_0
  - jeepney=0.4.2=py_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - json5=0.8.5=py_0
  - jsonschema=3.2.0=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.3.4=py36_0
  - jupyter_console=6.0.0=py36_0
  - jupyter_core=4.6.1=py36_0
  - jupyterlab=1.2.4=pyhf63ae98_0
  - jupyterlab_server=1.0.6=py_0
  - keras=2.3.1=py36_0
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - keyring=20.0.0=py36_0
  - kiwisolver=1.1.0=py36he6710b0_0
  - krb5=1.16.4=h173b8e3_0
  - lame=3.100=h14c3975_1001
  - lazy-object-proxy=1.4.3=py36h7b6447c_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libclang=9.0.1=default_hde54327_0
  - libcurl=7.67.0=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgpuarray=0.7.6=h14c3975_1003
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=14_mkl
  - liblapacke=3.8.0=14_mkl
  - libllvm9=9.0.1=hc9558a2_0
  - libopencv=4.2.0=py36_1
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.2=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.8.2=h1ba5d50_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libtool=2.4.6=h7b6447c_5
  - libuuid=2.32.1=h14c3975_1000
  - libuv=1.34.0=h516909a_0
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h1bed415_1
  - libxkbcommon=0.9.1=hebb1f50_0
  - libxml2=2.9.9=hea5a465_1
  - libxslt=1.1.33=h31b3aaa_0
  - llvmlite=0.31.0=py36hd408876_0
  - locket=0.2.0=py36_1
  - lxml=4.4.2=py36hefd8a0e_0
  - lz4-c=1.8.1.2=h14c3975_0
  - lzo=2.10=h49e0be7_2
  - mako=1.1.0=py_0
  - markdown=3.1.1=py36_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.1.2=py36_1
  - matplotlib-base=3.1.2=py36h250f245_1
  - mccabe=0.6.1=py36_1
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - mock=3.0.5=py36_0
  - more-itertools=8.0.2=py_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.1=hdf1c602_3
  - mpmath=1.1.0=py36_0
  - msgpack-python=0.6.1=py36hfd86e86_1
  - multipledispatch=0.6.0=py36_0
  - nbconvert=5.6.1=py36_0
  - nbformat=4.4.0=py36_0
  - ncurses=6.1=he6710b0_1
  - nettle=3.4.1=h1bed415_1002
  - networkx=2.4=py_0
  - nltk=3.4.5=py36_0
  - nodejs=13.7.0=h10a4023_0
  - nose=1.3.7=py36_2
  - notebook=6.0.2=py36_0
  - nspr=4.24=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numba=0.47.0=py36h962f231_0
  - numexpr=2.7.0=py36h9e4a6bb_0
  - numpy=1.17.4=py36hc1035e2_0
  - numpy-base=1.17.4=py36hde5b4d6_0
  - numpydoc=0.9.2=py_0
  - olefile=0.46=py36_0
  - opencv=4.2.0=py36_1
  - openh264=1.8.0=hdbcaa40_1000
  - openpyxl=3.0.2=py_0
  - openssl=1.1.1=h7b6447c_0
  - opt_einsum=3.1.0=py_0
  - packaging=20.0=py_0
  - pandas=0.25.3=py36he6710b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - pango=1.42.4=ha030887_1
  - parso=0.5.2=py_0
  - partd=1.1.0=py_0
  - path=13.1.0=py36_0
  - path.py=12.4.0=0
  - pathlib2=2.3.5=py36_0
  - patsy=0.5.1=py36_0
  - pcre=8.43=he6710b0_0
  - pep8=1.7.1=py36_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=7.0.0=py36hb39fc2d_0
  - pip=19.3.1=py36_0
  - pixman=0.38.0=h7b6447c_0
  - pluggy=0.13.1=py36_0
  - ply=3.11=py36_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py36_0
  - protobuf=3.11.2=py36he6710b0_0
  - psutil=5.6.7=py36h7b6447c_0
  - ptyprocess=0.6.0=py36_0
  - py=1.8.1=py_0
  - py-opencv=4.2.0=py36h5ca1d4c_1
  - pycodestyle=2.5.0=py36_0
  - pycosat=0.6.3=py36h7b6447c_0
  - pycparser=2.19=py36_0
  - pycrypto=2.6.1=py36h14c3975_9
  - pycurl=7.43.0.3=py36h1ba5d50_0
  - pyflakes=2.1.1=py36_0
  - pygments=2.5.2=py_0
  - pygpu=0.7.6=py36hc1659b7_1000
  - pylint=2.4.4=py36_0
  - pyodbc=4.0.27=py36he6710b0_0
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.12.3=py36hcca6a23_1
  - pyrsistent=0.15.6=py36h7b6447c_0
  - pysocks=1.7.1=py36_0
  - pytables=3.6.1=py36h9f153d1_0
  - pytest=5.3.2=py36_0
  - pytest-arraydiff=0.3=py36h39e3cac_0
  - pytest-astropy=0.7.0=py_0
  - pytest-astropy-header=0.1.1=py_0
  - pytest-doctestplus=0.5.0=py_0
  - pytest-openfiles=0.4.0=py_0
  - pytest-remotedata=0.3.2=py36_0
  - python=3.6.10=h0371630_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py36h7b6447c_0
  - pyyaml=5.2=py36h7b6447c_0
  - pyzmq=18.1.0=py36he6710b0_0
  - qt=5.12.5=hd8c4c69_1
  - qtawesome=0.6.0=py_0
  - qtconsole=4.6.0=py_1
  - qtpy=1.9.0=py_0
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py36_1
  - rope=0.14.0=py_0
  - ruamel_yaml=0.15.87=py36h7b6447c_0
  - scikit-image=0.15.0=py36he6710b0_0
  - scikit-learn=0.22.1=py36hd81dba3_0
  - scipy=1.3.2=py36h7c811a0_0
  - seaborn=0.9.0=pyh91ea838_1
  - secretstorage=3.1.1=py36_0
  - send2trash=1.5.0=py36_0
  - setuptools=44.0.0=py36_0
  - shapely=1.6.4=py36h5d51c17_1007
  - simplegeneric=0.8.1=py36_2
  - singledispatch=3.4.0.3=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.13.0=py36_0
  - snappy=1.1.7=hbae5bb6_3
  - snowballstemmer=2.0.0=py_0
  - sortedcollections=1.1.2=py36_0
  - sortedcontainers=2.1.0=py36_0
  - soupsieve=1.9.5=py36_0
  - sphinx=2.3.1=py_0
  - sphinxcontrib=1.0=py36_1
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - sphinxcontrib-websupport=1.1.2=py_0
  - spyder=3.3.6=py36_0
  - spyder-kernels=0.5.2=py36_0
  - sqlalchemy=1.3.12=py36h7b6447c_0
  - sqlite=3.30.1=h7b6447c_0
  - statsmodels=0.10.1=py36hdd07704_0
  - sympy=1.5.1=py36_0
  - tbb=2019.8=hfd86e86_0
  - tblib=1.6.0=py_0
  - tensorboard=2.0.0=pyhb38c66f_1
  - tensorflow=2.0.0=gpu_py36h6b29c10_0
  - tensorflow-base=2.0.0=gpu_py36h0ec5d1f_0
  - tensorflow-estimator=2.0.0=pyh2649769_0
  - tensorflow-gpu=2.0.0=h0d30ee6_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.3=py36_0
  - testpath=0.4.4=py_0
  - theano=0.9.0=py36_1
  - tk=8.6.10=hed695b0_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py36h7b6447c_0
  - tqdm=4.41.1=py_0
  - traitlets=4.3.3=py36_0
  - typed-ast=1.4.0=py36h7b6447c_0
  - unicodecsv=0.14.1=py36_0
  - unixodbc=2.3.7=h14c3975_0
  - urllib3=1.25.7=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - wrapt=1.11.2=py36h7b6447c_0
  - wurlitzer=2.0.0=py36_0
  - x264=1!152.20180806=h14c3975_0
  - xlrd=1.2.0=py36_0
  - xlsxwriter=1.2.7=py_0
  - xlwt=1.3.0=py36_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zict=1.0.0=py_0
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - aiohttp==3.6.2
    - async-timeout==3.0.1
    - efficientnet==1.0.0
    - idna-ssl==1.1.0
    - image-classifiers==1.0.0
    - jupyter-server-proxy==1.2.0
    - jupyterlab-nvdashboard==0.1.11
    - multidict==4.7.4
    - opencv-python==4.1.2.30
    - pynvml==8.0.4
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - segmentation-models==1.0.1
    - simpervisor==0.3
    - typing-extensions==3.7.4.1
    - yarl==1.4.2
prefix: /home/hasib/anaconda3/envs/hasib_gpu

